jlab/gapc

.travis.yml
aclocal.m4
configure
configure.ac
documentation/developer_notes
rtlib/hashtng.hh
rtlib/rope.hh
rtlib/string.cc
rtlib/string.hh

Text from @sgtkellox :
C++17 does not need you to specify the exception type in a methods signature. All exception throwing methods have a tag noexcept(false) in the signature. Type specifications may still occure in the throw call when a exception causing error is detected.
https://en.cppreference.com/w/cpp/language/except_spec

Migration to c17

---

src/lexer.l

necessary to avoid warning->error escalation in 20.10

avoid invalid conversion

---

testdata/ambiguitytest/run.sh

I saw OSX ambiguity tests failing, but when restarting the same code passed. I figure some tests are not stable to random effects. I guess it is test `specialization.test7Inst.baa.gap` and I am solving this by sorting the generated *.gap file prior to comparison against truth.

sort generated code prior to diff

---

debian/changelog
rtlib/terminal.hh
src/terminal.cc
testdata/grammar/testfloat.gap
testdata/regresstest/config

Although Georg's diss mentions a FLOAT terminal parse, it was not yet implemented. I've here added according code, but its current version is 
1. limited to simple xxx.yyyy float notation, i.e. no scientific notation like x.yyy+e06 
1. not performance optimized

adding FLOAT terminal parser

---

rtlib/terminal.hh
src/alt.cc
src/alt.hh
src/fn_decl.cc
src/type/base.cc
testdata/grammar2/testtermarg.gap
testdata/regresstest/config

extend the compiler such that the terminal parser `ROPE` can accept an argument (of type string) to restrict parses to this sequence of characters, e.g. `ROPE("kurt")` would now only yield an answer iff the sub-word is "kurt", not any other string. 
This is similar to `CHAR('A')`, but a bit more complicated since we want `ROPE` to know its now changes yield size.
Thus, `algfn(ROPE, X)` which has one moving boundary becomes `algfn(ROPE("kurt"), X)` without a moving boundary, since `ROPE` must consume exactly 4 characters.

Add term args

---

rtlib/rope.hh

added the missing operator `+=` for `Rope` which was called from auto generated count algebras in situations where a non terminal had multiple `ROPE` alternatives without having those wrapped into algebra functions.

Pluseq rope

---

rtlib/generic_main.cc
testdata/grammar/elm.gap
testdata/regresstest/config

adding a test case for missing header included when using `--float-accuracy`
A gapc call like `gapc --float-accuracy 2` generates code which fails to be compiled via g++ as it terminates complaining:
```
In file included from over_f1.hh:29:0,
from over_f1_main.cc:1:
Extensions/probing.hh: In function ‘void kmeans(int, int, double*, double*)’:
Extensions/probing.hh:26:36: warning: overflow in implicit constant conversion [-Woverflow]
int minDistIndex_point2cluster = HUGE_VAL;
^~~~~~~~
Extensions/probing.hh:47:35: warning: overflow in implicit constant conversion [-Woverflow]
minDistIndex_point2cluster = HUGE_VAL;
^~~~~~~~
over_f1_main.cc: In function ‘int main(int, char**)’:
over_f1_main.cc:68:21: error: ‘setprecision’ is not a member of ‘std’
std::cout << std::setprecision(FLOAT_ACC) << …
```

fix: --float-accuracy

---

src/backtrack.cc
src/kbacktrack.cc
src/subopt.cc
src/subopt_marker.cc

This is to fix warnings when **not** compiling in debug mode (assertions are not used):
```
g++  -I/usr/include   -O3  -std=c++17 -D_XOPEN_SOURCE=500 -MMD -MP -Wall -Wnon-virtual-dtor -Wno-unused-variable -Wno-parentheses -DNDEBUG -DBISONNEW   src/backtrack.cc -c -o src/backtrack.o 
src/backtrack.cc: In member function ‘virtual void Backtrack::gen_backtrack(AST&)’:
src/backtrack.cc:77:8: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
bool r = ast.check_instances(instance);
^
```

only execute checks in debug mode

---

.github/workflows/c-cpp.yml

I don't dare to change include locations at the moment for fear of side effects

turn of build/include_subdir warnings for now

---

src/algebra.cc
src/alt.cc
src/cpp.cc
src/gapc.cc
src/grammar.cc
src/printer.cc

This PR is to clean up the style of the generated CPP code, mostly 
- to move { into the same line as the function / statement
- systematically use indents
- use `""` over `<>` for includes
- remove space after `( `in function calls
- use `endl` instead of `\n`
I have to check all possible output, but only one out.cc / out.hh file for a simple MFE instance for nodangle grammar.

Refactor gencodestyle

---

src/alt.cc
src/alt.hh

moving adding filter_guards and for-loops in alt code generation into separate helper functions, such that outside code generation can easier call these functions in reverse order

swap order

---

.github/workflows/c-cpp.yml
src/alt.cc
src/alt.hh
src/const.cc
src/const.hh
src/expr.cc
src/expr.hh
src/gapc.cc
src/grammar.cc
src/grammar.hh
src/options.hh
src/specialize_grammar/create_specialized_grammar.cc
src/symbol.cc
src/symbol.hh
src/type/base.cc
src/type/base.hh
testdata/modtest/multi_plot_grammar.cc
testdata/modtest/multi_plot_grammar_full.cc

This PR adds a novel feature. With `--plot-grammar`, the user can request the generation of a out.dot file that holds a rudimentary graph representing the grammar. This is handy if the grammar is modified by the compiler.
This is not yet complete! Missing:

Plot Grammar

---

src/alt.cc

found a stupid copy&paste error, which resulted in printing left-index twice, instead of left- and right-index

print right index

---

src/alt.cc

Indices for terminals and non-terminals left of the outside-NT were incremented by yield size, but they have to be decremented. Otherwise, we have negative sub-word intervals!

Fix outside plusminus

---

librna/rnalib.c

In order to reduce the execution time of some Gapc compilations, we figured it would make sense to precalculate (most of) the required return values of the `scale` function from the [rnalib.c](https://github.com/jlab/gapc/blob/master/librna/rnalib.c)-file, since this function is called quite often in the return statements of certain algebra functions. As expected, precalculating the scale values reduces the execution time of the Gapc compilation I tested (`gapc -p alg_pfunc nodangle.gap`) by a significant amount (see benchmark below).
I once again tested multiple scale value lookup implementations (dynamic lookup (blue line), full precalculation) and concluded that precalculating the scale values beforehand as well as moving this process to a dedicated function reduces the execution time …

precalculate the first 10000 scale values

---

librna/rnalib.c

Similarly to the last PR #154 , I figured it would also makes sense to precalculate a relatively large amount of the scaled energy values the `mk_pf` function from the [rnalib.c](https://github.com/jlab/gapc/blob/master/librna/rnalib.c)-file returns, since this function is also called quite often in the return statements of certain algebra functions.
As you can see in the benchmark plot above, precalulating just the first 10000 `mk_pf` scaled energy values reduces the execution time of the Gapc compilation I tested (`gapc -p alg_pfunc nodangle.gap`) by about as much as is theoretically possible for this particular function (see green line for maximum possible speedup), while only minimally increasing the required memory (by such a small amount that you can't even see it in the memory …

precalculate mk_pf energy scaling values

---

src/alt.cc
src/alt.hh

Algebra functions can have additional parameters as further inputs besides sub-parses, see https://github.com/jlab/gapc/blob/master/testdata/grammar/empty_ys_issue_larger.gap or https://github.com/jlab/gapc/blob/master/testdata/grammar/pknotsRG.gap for examples. Signature, grammar, and algebra definitions look like this:
```
answer right_transition(float, answer, alphabet; int);
```
```
right_transition(CONST_FLOAT(-1.823000), state_IR_19, CHAR; 19)
```
```
float right_transition(float tsc, float x, alphabet a; int pos) {
return tsc + getEmission(pos, a) + x;
}
```
These parameters are currently **not** printed into the out.dot file when `gapc` is invoked with the `plot-grammar X` command line argument. A resulting PDF currently looks like:
With this PR the updated graphic should include …

Plot optional non-terminal parameters

---

.github/workflows/c-cpp.yml
src/alt.cc
src/alt.hh
src/gapc.cc
src/symbol.cc
testdata/modtest/multi_plot_grammar_level3.cc
testdata/modtest/multi_plot_grammar_level5.cc

I am extending the level of detail for generating graphViz code about the used grammar. Two additional levels can be selected by the user with this PR:
4) which will also add one line per track for the minimal and maximal yield size of each grammar component. The yield size determines how many terminals can be parsed at least = minimal and at most = maximal, which can be `n` if infinite terminals are consumable
5) lhs non-terminal symbols will have additional lines describing the table layout necessary for tabulation (and on demand computation) like quadratic (default), linear or constant tables.
I also re-design the gold standards for plot-grammar functionality. We now have three levels tested: 1, 3, 5. Instead of 1 and `full` as before, since full was too unspecific and probably makes …

Plotgrammar add ys tabdim

---

src/plot_grammar.cc

In current grammar plots `--plot-grammar 1`, the alignment of the non-terminals, which are placed below each other, is not properly left aligned, e.g.
This PR uses a different mechanism to inject invisible nodes to force the layout of `dot` to almost perfectly left align all `subgraphs`. We therefore place only one invisible node at the lowest rank per non-terminal, connect this node a) with the lhs non-terminal node and b) with the next lhs non-terminal of the following subgraph. It is important to make the shape rectangular and use proper `ports` for the edge connection, i.e. `sw` to `nw`. We therefore have to return the nodeID of one of the lowest nodes per non-terminal subgraph in addition to the already returned `max_depth`. The result looks visually more pleasing:
However, these …

proper align non terminals in grammar plots

---

src/cpp.cc

This PR should fix the bug from [this issue](https://github.com/jlab/gapc/issues/196).

fix wrong variable name

---

.github/workflows/c-cpp.yml
src/fn_arg.cc
src/fn_arg.hh
src/parser.y
src/specialize_grammar/create_specialized_grammar.cc

Production rules in grammars can use two types of special terminal parser. The first is a terminal parser specialized to certain inputs, e.g. `CHAR` can be specialized to just accept a letter `A` like `CHAR('A')`. Yield of this terminal parser is (1, 1).
The second type of special terminal parser is a construct that not really parses parts of the input but is handy to inject parameters to algebra functions, like `foo(CONST_CHAR('x'), ...)`. One might use algebra function `foo` in different rules in the algebra with different constants, another rule could be `foo(CONST_CHAR('y'), ...)`. These terminal parser must have a yield size of (0, 0) as the do not advance in parsing inputs.
Currently, the yield of the `Fn_Arg::Const` was computed incorrectly, i.e. second type did get a non zero …

set yield size of CONST_ terminal parser to (0,0)

---

src/outside/middle_end.cc
src/outside/middle_end.hh

passing iterators to sum_ys() led to wrong results only on OSx (ubuntu worked fine). I changed the logic such we now only pass the start element position, i.e. size_t instead of iterators

fix sum_ys error on OSX

---

.github/workflows/c-cpp.yml
src/alt.cc
src/alt.hh
src/grammar.cc
src/outside/middle_end.cc
testdata/grammar2/alignments_cyk.gap
testdata/regresstest/config

This PR shall fix a situation where gapc ran into an infinite loop:
1. somehow the outside_init_indices function was able to add the same loop onto the loops list, which led - due to the nesting of all loops - to an infinitely nested loop structure. I resolved this by first checking if the loop is already contained in the list, only if not, it gets added.
2. next, the compiled binary ran into an infinite recursion of non terminals, because the table design was incorrect for multi track grammars. I am not sure if this might be a general issue (also for old inside parts) or specific for the outside addition. However, resetting the bool `table_dim_ready` flag for NTs prior to next track iteration solved this issue

Outside fix infloop

---

src/fn_arg.hh
src/plot_grammar.cc

Properly escape `CHAR('&')` via `CHAR('&amp;')` for graphviz output to avoid e.g.

escape CHAR('&') for plot-grammar

---

.github/workflows/c-cpp.yml
src/plot_grammar.cc
src/plot_grammar.hh

This PR prepares tikz auto algebra generation as it exposes color definitions of plot-grammar via a header file. Furthermore, as our target language will be tikZ=latex, we can no longer use a mix of hex and named colors, thus converting every color to hex.

Redefine grammar colors

---

src/grammar.cc

the init_indices() function can be called multiple times, i.e. two times for backtraceing. The left/right_running_indices are not empty in the second traversal. Instead of asserting emptiness, we now simply clear both containers upfront.

clear left/right running indices
